name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read # No package write permission needed for npmjs.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version
          registry-url: 'https://registry.npmjs.org' # Set the registry URL for npm

      - name: Read package.json
        id: package
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Verify tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [ "$TAG" != "v${{ steps.package.outputs.version }}" ]; then
            echo "Tag $TAG does not match package.json version v${{ steps.package.outputs.version }}"
            exit 1
          fi
      
      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use NODE_AUTH_TOKEN with actions/setup-node
